amcl:
  ros__parameters:
    alpha1: 3.5
    alpha2: 0.35
    alpha3: 0.3
    alpha4: 0.7
    alpha5: 0.4
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 3.0 # For obstacles detection, Default: 2.0s
    laser_max_range: 50.0 # Default: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.1 # Particle filter error
    pf_z: 0.99 # Particle filter z 
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::OmniMotionModel"
    save_pose_rate: 0.1
    sigma_hit: 0.1
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.005 # Update per rotational movement
    update_min_d: 0.05 # Update per translational movement
    z_hit: 0.9 # Adjust this to match the laser scan to map
    z_max: 0.95 #
    z_rand: 0.35 #
    z_short: 0.05 #
    scan_topic: scan

bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odometry/filtered
    bt_loop_duration: 10
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    action_server_result_timeout: 900.0
    navigators: ["navigate_to_pose", "navigate_through_poses"]
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"
    # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
    # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
    # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
    # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.

    # plugin_lib_names is used to add custom BT plugins to the executor (vector of strings).
    # Built-in plugins are added automatically
    # plugin_lib_names: 

    error_code_name_prefixes:
      - assisted_teleop
      - backup
      - compute_path
      - dock_robot
      - drive_on_heading
      - follow_path
      - nav_thru_poses
      - nav_to_pose
      - route
      - spin
      - undock_robot
      - wait

controller_server:
  ros__parameters:
    controller_frequency: 30.0
    costmap_update_timeout: 0.30
    min_x_velocity_threshold: 0.01
    min_y_velocity_threshold: 0.01
    min_theta_velocity_threshold: 0.01
    failure_tolerance: 0.3
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"] # "precise_goal_checker"
    controller_plugins: ["FollowPath"]
    odom_topic: /odometry/filtered
    use_realtime_priority: false
    enable_stamped_cmd_vel: false
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.35
      yaw_goal_tolerance: 0.5
    FollowPath:
        plugin: "omni_carver_pure_pursuit::PurePursuitController"
        debug_trajectory_details: False
        desired_linear_vel: 0.14
        lookahead_dist: 0.4
        max_angular_vel: 0.17
        yaw_gain: 1.0
        transform_tolerance: 1.0
    # FollowPath:
    #   plugin: "omni_sbmpo_controller::OmniSBMPOController"

    #   # ————————————————————————————————
    #   # Omni‐SBMPO parameters for X/Y
    #   # ————————————————————————————————
    #   # simulation
    #   horizon:      2.5
    #   dt:           0.2

    #   # how many samples in X and Y
    #   num_samples_vx: 10
    #   num_samples_vy: 10
    #   num_samples_w:  10

    #   # maximum commanded speeds in each axis
    #   vx_max: 0.07
    #   vy_max: 0.07
    #   w_max:  0.12

    #   # cost‐function weights
    #   obstacle_weight:         15.0
    #   path_weight:             0.2
    #   forward_reward:          0.4

    #   # obstacle handling
    #   obstacle_threshold:      30
    #   penalty_factor:          300.0
    #   emergency_ttc:           0.5
    #   clearance_penalty_weight: 2.0

 
    # FollowPath:
    #   plugin: "iterative_lqr_controller::IterativeLQRController"
    #   horizon:       10
    #   dt:            0.1
    #   Q_x:           10.0
    #   Q_y:           10.0
    #   R_vx:          1.0
    #   R_vy:          1.0
    #   max_vel_x:     0.07
    #   max_vel_y:     0.07
    #   max_vel_theta: 0.12

    # FollowPath:
    #   plugin: "nav2_mppi_controller::MPPIController"
    #   time_steps: 15
    #   model_dt: 0.2
    #   batch_size: 2000
    #   ax_max: 3.0
    #   ax_min: -3.0
    #   ay_max: 3.0
    #   az_max: 3.5
    #   vx_std: 0.2
    #   vy_std: 0.2
    #   wz_std: 0.4
    #   vx_max: 0.17
    #   vx_min: -0.2
    #   vy_max: 0.17
    #   wz_max: 0.3
    #   iteration_count: 1
    #   prune_distance: 1.7
    #   transform_tolerance: 0.1
    #   temperature: 0.3
    #   gamma: 0.015
    #   motion_model: "Omni"
    #   visualize: false
    #   regenerate_noises: false
    #   TrajectoryVisualizer:
    #     trajectory_step: 5
    #     time_step: 3
    #   AckermannConstraints:
    #     min_turning_r: 0.2
    #   critics: [
    #     "ConstraintCritic", "CostCritic", "GoalCritic",
    #     "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic",
    #     "PathAngleCritic", "PreferForwardCritic"]
    #   ConstraintCritic:
    #     enabled: true
    #     cost_power: 1
    #     cost_weight: 4.0
    #   GoalCritic:
    #     enabled: true
    #     cost_power: 1
    #     cost_weight: 5.0
    #     threshold_to_consider: 1.4
    #   GoalAngleCritic:
    #     enabled: true
    #     cost_power: 1
    #     cost_weight: 3.0
    #     threshold_to_consider: 0.5
    #   PreferForwardCritic:
    #     enabled: true
    #     cost_power: 1
    #     cost_weight: 5.0
    #     threshold_to_consider: 0.5
    #   CostCritic:
    #     enabled: true
    #     cost_power: 1
    #     cost_weight: 3.81
    #     critical_cost: 300.0
    #     consider_footprint: true
    #     collision_cost: 1000000.0
    #     near_goal_distance: 1.0
    #     trajectory_point_step: 2
    #   PathAlignCritic:
    #     enabled: true
    #     cost_power: 1
    #     cost_weight: 14.0
    #     max_path_occupancy_ratio: 0.05
    #     trajectory_point_step: 4
    #     threshold_to_consider: 0.5
    #     offset_from_furthest: 20
    #     use_path_orientations: false
    #   PathFollowCritic:
    #     enabled: true
    #     cost_power: 1
    #     cost_weight: 5.0
    #     offset_from_furthest: 5
    #     threshold_to_consider: 1.4
    #   PathAngleCritic:
    #     enabled: true
    #     cost_power: 1
    #     cost_weight: 2.0
    #     offset_from_furthest: 4
    #     threshold_to_consider: 0.5
    #     max_angle_to_furthest: 1.0
    #     mode: 0

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 5.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.5
      plugins: ["obstacle_layer", "inflation_layer"]
      filters: ["keepout_filter"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        footprint_clearing_enabled: True
        max_obstacle_height: 2.0
        combination_method: 1
        observation_sources: scan
        scan:
          topic: "/scan"
          sensor_frame: "laser_link"
          data_type: "LaserScan"
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0
          inf_is_valid: False
          marking: True
          clearing: True
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.75
        inflation_radius: 2.35
      # denoise_layer:
      #   plugin: "nav2_costmap_2d::DenoiseLayer"
      #   enabled: False
      #   minimal_group_size: 2
      #   group_connectivity_type: 8
      keepout_filter:
          plugin: "nav2_costmap_2d::KeepoutFilter"
          enabled: True
          filter_info_topic: "/costmap_filter_info"
      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 5.0
      global_frame: map
      robot_base_frame: base_link
      robot_radius: 0.5
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer", "denoise_layer"]
      filters: ["keepout_filter"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        footprint_clearing_enabled: True
        max_obstacle_height: 2.0
        combination_method: 1
        observation_sources: scan
        scan:
          topic: "/scan"
          sensor_frame: "laser_link"
          data_type: "LaserScan"
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0
          inf_is_valid: False
          marking: True
          clearing: True
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        footprint_clearing_enabled: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 1.75
        inflation_radius: 2.35
      denoise_layer:
        plugin: "nav2_costmap_2d::DenoiseLayer"
        enabled: True
        minimal_group_size: 2
        group_connectivity_type: 8
      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"
      always_send_full_costmap: True

# The yaml_filename does not need to be specified since it going to be set by defaults in launch.
# If you'd rather set it in the yaml, remove the default "map" value in the tb3_simulation_launch.py
# file & provide full path to map below. If CLI map configuration or launch default is provided, that will be used.
map_server:
  ros__parameters:
    yaml_filename: ""

map_saver:
  ros__parameters:
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    planner_plugins: ["GridBased"]
    costmap_update_timeout: 1.0
    HybridAStar:
      plugin: "HybridAStar"
      step_size: 0.5
      analytic_expansion_freq: 20

smoother_server:
  ros__parameters:
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True

behavior_server:
  ros__parameters:
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    wait:
      plugin: "nav2_behaviors::Wait"
    assisted_teleop:
      plugin: "nav2_behaviors::AssistedTeleop"
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 0.1
    min_rotational_vel: 0.01
    rotational_acc_lim: 3.0
    enable_stamped_cmd_vel: false

waypoint_follower:
  ros__parameters:
    loop_rate: 2
    stop_on_failure: false
    action_server_result_timeout: 900.0
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.14, 0.14, 0.17]
    min_velocity: [-0.14, -0.14, -0.17]
    max_accel: [0.1, 0.1, 3.0]
    max_decel: [-0.5, -0.5, -3.0]
    odom_topic: "/odometry/filtered"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0
    enable_stamped_cmd_vel: false

costmap_filter_info_server:
  ros__parameters:
    use_sim_time: false
    type: 0
    filter_info_topic: "/costmap_filter_info"
    mask_topic: "/keepout_filter_mask"
    base: 0.0
    multiplier: 1.0

filter_mask_server:
  ros__parameters:
    use_sim_time: false
    frame_id: "map"
    topic_name: "/keepout_filter_mask"
    yaml_filename: "/home/carver/omni-carver/src/omni_carver_nav2/maps/map_7_keepout.yaml"