<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="twheel">
    <xacro:include filename="$(find twheel_description)/urdf/properties.xacro"/>
    <xacro:include filename="$(find twheel_description)/urdf/base.xacro"/>
    <xacro:include filename="$(find twheel_description)/urdf/wheel.xacro"/>
    <xacro:include filename="$(find twheel_description)/urdf/sensor.xacro"/>
    
    <xacro:base path="package://${PACKAGE_NAME}/${BASE_MESH_PATH}"/>
    <xacro:wheel name="left" translation_y="${WHEEL_SEPARATION/2}"/>
    <xacro:wheel name="right" translation_y="${-WHEEL_SEPARATION/2}"/>
    <xacro:sensor_link/>
</robot>
