<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="twheel">
    <xacro:include filename="$(find twheel_description)/urdf/properties.xacro"/>
    
    <xacro:macro name="wheel" params="name translation_y">
        <link name="${name}_wheel">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_THICKNESS}"/>
                </geometry>
                <material name="${name}_wheel_color">
                    <color rgba="${WHEEL_COLOR}"/>
                </material>
            </visual>
            <inertial>
                <origin xyz="${WHEEL_COM}"/>
                <mass value="${WHEEL_M}"/>
                <inertia 
                  ixx="${WHEEL_Ixx}"
                  ixy="${WHEEL_Ixy}"
                  ixz="${WHEEL_Ixz}"
                  iyy="${WHEEL_Iyy}"
                  iyz="${WHEEL_Iyz}"
                  izz="${WHEEL_Izz}" 
                />
            </inertial>
            <collision>
                <geometry>
                    <cylinder radius="${WHEEL_RADIUS}" length="${WHEEL_THICKNESS}"/>
                </geometry>
                <surface>
                    <friction>
                        <ode>
                            <mu>1000</mu>
                            <mu2>1000</mu2>
                        </ode>
                    </friction>
                </surface>
            </collision>
        </link>
        <joint name="${name}_wheel_joint" type="continuous">
            <origin xyz="0.0 ${translation_y} ${WHEEL_RADIUS-(BASE_HEIGHT/2+BASE_ELEVATION)}" rpy="${-PI/2} 0.0 0.0"/>
            <parent link="base_link"/>
            <child link="${name}_wheel"/>
            <axis xyz="0.0 0.0 1.0"/>
            <joint_properties damping="1.0" friction="1.0"/>
        </joint>
    </xacro:macro>
</robot>
