controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controllers:
      type: velocity_controllers/JointGroupVelocityController

velocity_controllers:
  ros__parameters:
    joints: 
      - rim_right_joint
      - rim_left_joint
      - rim_back_joint
    command_interface: 
      - velocity
    state_interface:
      - position
      - velocity
      - effort
    pid: {p: 0.001, i: 0.0, d: 0.0}

# velocity_controllers:
#   ros__parameters:
#     joints: 
#       - wheel1_joint
#       - wheel2_joint
#       - wheel3_joint
#     command_interface: 
#       - velocity
#     state_interface:
#       - position
#       - velocity
#       - effort
#     pid: {p: 0.001, i: 0.0, d: 0.0}
